[versions]

# Minecraft
minecraft_version = "1.16.5"
minecraft_required = "1.14"
minecraft_compatible = "1.14,1.14.1,1.14.2,1.14.3,1.14.4,1.15,1.15.1,1.15.2,1.16,1.16.1,1.16.2,1.16.3,1.16.4,1.16.5,1.17,1.17.1,1.18,1.18.1,1.18.2,1.19,1.19.1,1.19.2,1.19.3,1.19.4,1.20,1.20.1,1.20.2"

fabric_loader = "0.14.21"
fabric_yarn = "1.16.5+build.10"

# Libraries
annotations = "24.0.1"

# Plugins
loom = "1.+"
minotaur = "2.+"

[libraries]
# Minecraft
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft_version" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_yarn = { module = "net.fabricmc:yarn", version.ref = "fabric_yarn" }

# Libraries
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

[bundles]
compile = ["annotations"]
mod_dependency = []
mod_runtime = []

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
